### ISSUE TITLE
websocketの誤った使い方でpanicで落ちる

### ISSUE THREAD

**Issue by himananiito** [himananiito/livedl#1]
~~~
panic: concurrent write to websocket connection

goroutine 51 [running]:
github.com/gorilla/websocket.(*messageWriter).flushFrame(0xc04237a180, 0xad8301, 0x0, 0x0, 0x0, 0xacb760, 0xa25100)
	*********************/github.com/gorilla/websocket/conn.go:588 +0x681
github.com/gorilla/websocket.(*messageWriter).Close(0xc04237a180, 0xa76840, 0xc04237a150)
	*********************/github.com/gorilla/websocket/conn.go:702 +0x66
github.com/gorilla/websocket.(*Conn).WriteJSON(0xc042062c80, 0xa76840, 0xc04237a150, 0x4, 0xc0422a81b8)
	*********************/github.com/gorilla/websocket/json.go:29 +0x119
_/C_/work/livedl/src/niconico.(*NicoHls).startMain.func1(0xc0422ac1e0, 0x0)
	*******/livedl/src/niconico/nico_hls.go:1605 +0x1e12
_/C_/work/livedl/src/niconico.(*NicoHls).startGoroutine2.func1(0xc04222ea00, 0xc0422ac1e0, 0xc0422a6000, 0x0)
	*******/livedl/src/niconico/nico_hls.go:592 +0x3b
created by _/C_/work/livedl/src/niconico.(*NicoHls).startGoroutine2
	*******/livedl/src/niconico/nico_hls.go:590 +0x9d
~~~

**Comment by himananiito** [comment]
対応：以下のように排他ロックを取る。
https://github.com/gorilla/websocket/issues/119

Data Race Detectorでこのようなバグを見つける
