### ISSUE TITLE
[ツイキャス] リトライ機能中に途中でエラーとなる

### ISSUE THREAD

**Issue by himananiito** [himananiito/livedl#11]
- ログ
```
panic: runtime error: invalid memory address or nil pointer dereference
        panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x727d09]

goroutine 1 [running]:
github.com/gorilla/websocket.(*Conn).Close(0x0, 0x0, 0x0)
        *********************/github.com/gorilla/websocket/conn.go:348 +0x29
panic(0xa75ba0, 0xf586d0)
        *********/runtime/panic.go:505 +0x237
github.com/gorilla/websocket.(*Conn).SetReadDeadline(0x0, 0xbee208fcdc517fe0, 0x53c5df8dd45, 0xf86cc0, 0xbee208fcdc517fe0, 0x53c5df8dd45)
        *********************/github.com/gorilla/websocket/conn.go:1035 +0x29
*********/livedl/src/twitcas.TwitcasRecord(0xc0420160e0, 0xa, 0x0, 0x0, 0xffffffffffff0000)
        *******/livedl/src/twitcas/twicas.go:229 +0x4cc
main.main()
        *******/livedl/src/livedl.go:60 +0x478
```

**Comment by himananiito** [comment]
- 原因
connがnilであるのにerrもnil（errに正しく設定できていない）となることがあるミスのためにconn.SetReadDeadlineで落ちていた。

```
-       resp, e := client.Do(req)
-       if e != nil {

+       resp, err := client.Do(req)
+       if err != nil {
```
